{
 "title": "Service - Health Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "service",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "Service Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "$service - Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{namespace=\"$namespace\",container=~\"$service\"})",
     "legendFormat": "$service"
    }
   ]
  },
  {
   "title": "$service - CPU Usage  (Should be Non-Zero)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(pod) (\r\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=~\".*$service.*\"}[5m])\r\n)\r\n/\r\nsum by(pod) (\r\n  kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", container=~\".*$service.*\"}\r\n)\r\n* 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$service - Memory Usage  (Should be Non-Zero)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(pod) (\r\n  container_memory_usage_bytes{namespace=\"$namespace\", container=~\".*$service.*\"}\r\n)\r\n/\r\nsum by(pod) (\r\n  kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", container=~\".*$service.*\"}\r\n)\r\n* 100",
     "legendFormat": "{{pod}} - {{node}}"
    }
   ]
  },
  {
   "title": "$service - CPU Usage  (apps without resource limit defined) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "CPU Cores" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=~\"$service.*\"}[$__rate_interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$service - Memory Usage  (apps without resource limits)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_usage_bytes{namespace=\"$namespace\", container=~\"$service.*\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}