apiVersion: v2
name: kube-prometheus-stack-wrapper
version: "0.0.3"
dependencies:
- name: kube-prometheus-stack
  version: "66.2.1"
  repository: https://prometheus-community.github.io/helm-charts
  condition: kube-prometheus-stack.enabled
- name: prometheus-blackbox-exporter
  version: "9.1.0"
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus-blackbox-exporter.enabled
- name: prometheus-msteams
  version: "1.3.4"
  repository: https://prometheus-msteams.github.io/prometheus-msteams/
  condition: prometheus-msteams.enabled
- name: loki
  version: "6.25.0"
  repository: https://grafana.github.io/helm-charts
  condition: loki.enabled
- name: promtail
  version: "6.16.6"
  repository: https://grafana.github.io/helm-charts
  condition: promtail.enabled
# - name: kubernetes-event-exporter
#   repository: https://charts.bitnami.com/bitnami
#   version: "3.4.4"
#   condition: kubernetes-event-exporter.enabled