{{- $promtail := index .Values "promtail" "enabled"|default false -}}
{{- if $promtail }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-promtail
  labels:
    {{/*- include "promtail.labels" . | nindent 4 */}}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
      - pods/log
    verbs:
      - get
      - watch
      - list
{{- end }}