{{- $grafana := index .Values "kube-prometheus-stack" "grafana" "enabled"|default false -}}
{{- if $grafana }}
{{ range $path, $_ :=  .Files.Glob  "grafana.folders/*.yaml" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-grafana-folders
  labels:
    grafana_folder: "1"
data:
  {{ base $path |lower | replace "_" "-" | replace " " "-" | quote }}: |
{{ $.Files.Get $path |indent 4 }}
{{ end }}
{{ end }}