{{- $values := .Values }}
{{- $chart := .Chart }}
{{- range $item := $values.spec.destinations }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-{{ $item.cluster }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $values.spec.project }}
  source:
    path: cert-manager/versions/{{ $item.version }}
    repoURL: {{ $values.spec.source.repoURL }}
    targetRevision: {{ $values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
        {{- range $item.additionalValueFiles }}
        - {{ . }}
        {{- end}}
  destination:
    namespace: {{ $item.namespace }}
    server: {{ $item.server }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
