apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ctrl-cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    path: cert-manager/argo-apps
    repoURL: https://git.crisp.rbro.rbg.cc/CRISP/infrastructure-kubernetes.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
#   - Replace=true
