{
 "title": "Monitoring System / Loki",
 "description": "Loki Metrics",
 "tags": [
  "Loki",
  "Prometheus",
  "Crisp- DevOps",
  "Kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Loki Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_build_info" }
   ]
  },
  {
   "title": "canary down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_desired_number_scheduled{daemonset=~\"loki-canary\"} - kube_daemonset_status_number_ready{daemonset=~\"loki-canary\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "distributor down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*-loki-distributor\"} - kube_deployment_status_replicas_ready{deployment=~\".*-loki-distributor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "compactor down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=~\".*-loki-compactor.*\"} - kube_statefulset_status_replicas_available{statefulset=~\".*-loki-compactor.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ingester-z-a down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=~\".*loki-ingester-zone-a.*\"} - kube_statefulset_status_replicas_available{statefulset=~\".*loki-ingester-zone-a.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rules Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_rule_group_rules)"
    }
   ]
  },
  {
   "title": "Store Chunks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_chunk_stored_bytes_total)"
    }
   ]
  },
  {
   "title": "Panic ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(loki_panic_total)" }
   ]
  },
  {
   "title": "Minio Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "minio_software_version_info" }
   ]
  },
  {
   "title": "minio down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=~\".*minio.*\"} - kube_statefulset_status_replicas_available{statefulset=~\".*minio.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "index-gateway down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=~\".*loki-index-gateway\"} - kube_statefulset_status_replicas_available{statefulset=~\".*loki-index-gateway.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "compactor down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=~\".*-loki-compactor.*\"} - kube_statefulset_status_replicas_available{statefulset=~\".*-loki-compactor.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ingester-z-b down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=~\".*loki-ingester-zone-b.*\"} - kube_statefulset_status_replicas_available{statefulset=~\".*loki-ingester-zone-b.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Store Series Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(loki_store_series_total)" }
   ]
  },
  {
   "title": "Message Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(loki_log_messages_total)" }
   ]
  },
  {
   "title": "Helmchart Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "chuk-cache down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=~\".*-loki-chunks-cache.*\"} - kube_statefulset_status_replicas_available{statefulset=~\".*-loki-chunks-cache.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "results-cache down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=~\".*-loki-results-cache.*\"} - kube_statefulset_status_replicas_available{statefulset=~\".*-loki-results-cache.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ruler down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=~\".*-loki-ruler.*\"} - kube_statefulset_status_replicas_available{statefulset=~\".*-loki-ruler.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ingester-z-c down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=~\".*loki-ingester-zone-c.*\"} - kube_statefulset_status_replicas_available{statefulset=~\".*loki-ingester-zone-c.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Loki", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Messages Input",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(loki_log_messages_total[1m])) by (level)",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "S3 Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_s3_request_duration_seconds_bucket[5m])) by (le,operation))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "API Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket[5m])) by (le,route))",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "LogQL Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "LogQL  Processed bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Ruler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rules Status ",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(prometheus_rule_evaluations_total)",
       "legendFormat": "Evaluations"
      },
      {
       "expr": "sum(prometheus_notifications_sent_total)",
       "legendFormat": "Notifications"
      }
     ]
    },
    {
     "title": "Notifications Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_notifications_latency_seconds[5m]))  by (quantile)",
       "legendFormat": "TP {{quantile}}"
      }
     ]
    },
    {
     "title": "Rule Evaluations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_rule_evaluation_duration_seconds[5m]))  by (quantile)",
       "legendFormat": "TP {{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Request  Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_cache_request_duration_seconds_bucket[5m])) by (le,name,method))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Cache Value Size bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_cache_value_size_bytes_bucket[5m])) by (le,name,method))",
       "legendFormat": "{{name}} / {{method}}"
      }
     ]
    },
    {
     "title": "Hits Keys",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "rate(loki_cache_hits[5m])", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Background Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "loki_cache_background_queue_length",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Fetched Keys",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "loki_cache_fetched_keys", "legendFormat": "{{name}}" }
     ]
    }
   ]
  },
  {
   "title": "Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 Request Durations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 389 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_s3_request_duration_seconds_bucket[5m])) by (le,operation))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Chunk Store Chunks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 389 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_chunk_store_chunks_per_query_bucket[5m])) by (le))",
       "legendFormat": "chunks"
      }
     ]
    },
    {
     "title": "Table-Manager Sync Durations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 389 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_tsdb_shipper_tables_sync_operation_total[5m])) by (le))"
      }
     ]
    }
   ]
  },
  {
   "title": "Distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Lines / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 396 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (tenant) (rate(loki_distributor_lines_received_total[5m]))",
       "legendFormat": "distributor / {{ tenant}}"
      }
     ]
    },
    {
     "title": "Distributor  Received bytes / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 396 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_bytes_received_total[5m])) by (tenant)",
       "legendFormat": "distributor / {{tenant}}"
      }
     ]
    },
    {
     "title": "batch appends sent to ingesters / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 396 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(loki_distributor_ingester_appends_total[5m])",
       "legendFormat": "successed"
      },
      {
       "expr": "loki_distributor_ingester_append_failures_total",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "Store Series / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 396 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(loki_store_series_total[5m]))",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocks / Chunk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_blocks_per_chunk_bucket[5m])) by (le))",
       "legendFormat": "blocks"
      }
     ]
    },
    {
     "title": "Chunk Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket[5m])) by (le))",
       "legendFormat": "chunk size"
      }
     ]
    },
    {
     "title": "Chunk Age",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_age_seconds_bucket[5m])) by (le))",
       "legendFormat": "ages"
      }
     ]
    },
    {
     "title": "Chunk Compression Ratios",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket[5m])) by (le))",
       "legendFormat": "ratio"
      }
     ]
    },
    {
     "title": "Chunk Encode Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_encode_time_seconds_bucket[5m])) by (le))",
       "legendFormat": "durations."
      }
     ]
    },
    {
     "title": "Lines / Chunk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_entries_bucket[5m])) by (le))",
       "legendFormat": "lines"
      }
     ]
    },
    {
     "title": "Chunk Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(loki_ingester_chunks_created_total[5m])",
       "legendFormat": "create"
      },
      {
       "expr": "sum by (reason) (rate(loki_ingester_chunks_flushed_total[5m]))",
       "legendFormat": "flush / {{ reason }}"
      },
      {
       "expr": "sum by (fake) (rate(loki_ingester_chunks_stored_total[5m]))",
       "legendFormat": "stored"
      },
      {}
     ]
    },
    {
     "title": "Chunks in Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "loki_ingester_memory_chunks", "legendFormat": "chunks" }
     ]
    },
    {
     "title": "Chunks in Streams",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (tenan) (loki_ingester_memory_streams)",
       "legendFormat": "streams"
      }
     ]
    },
    {
     "title": "Strams Stats",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(loki_ingester_streams_created_total[5m])",
       "legendFormat": "create"
      },
      {
       "expr": "rate(loki_ingester_streams_removed_total[5m])",
       "legendFormat": "delete"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage by pod, container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\".*(loki|minio|promtail).*\", container!=\"\"}[$__rate_interval])) by (pod, container)",
       "legendFormat": "{{ pod }} - {{ container }}"
      }
     ]
    },
    {
     "title": "Memory Usage by container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{pod=~\".*(loki|minio|promtail).*\", image!=\"\", container!=\"\"}) by (pod, container)",
       "legendFormat": "{{ pod }} - {{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Persistent Volumes - Capacity and usage in %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*minio.*\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*minio.*\"}) by (persistentvolumeclaim)",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    },
    {
     "title": "Persistent Volumes - Capacity and usage in bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*minio.*\"}) by (persistentvolumeclaim)",
       "legendFormat": "{{ persistentvolumeclaim }} - Used"
      },
      {
       "expr": "sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*minio.*\"}) by (persistentvolumeclaim)",
       "legendFormat": "{{ persistentvolumeclaim }} - Capacity"
      }
     ]
    },
    {
     "title": "Persistent Volumes - Inodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - sum(kubelet_volume_stats_inodes_used{persistentvolumeclaim=~\".*minio.*\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_inodes{persistentvolumeclaim=~\".*minio.*\"}) by (persistentvolumeclaim)",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network - Bandwidth by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{pod=~\".*(loki|minio|promtail).*\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{pod=~\".*(loki|minio|promtail).*\"}[$__rate_interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network - Errors by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_errors_total{pod=~\".*(loki|minio|promtail).*\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Received"
      },
      {
       "expr": "- sum(rate(container_network_transmit_errors_total{pod=~\".*(loki|minio|promtail).*\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Transmitted"
      }
     ]
    },
    {
     "title": "Network - Packets Dropped by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{pod=~\".*(loki|minio|promtail)*\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Received"
      },
      {
       "expr": "- sum(rate(container_network_transmit_packets_dropped_total{pod=~\".*(loki|minio|promtail)*\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Transmitted"
      }
     ]
    },
    {
     "title": "Network - Packets rate by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{pod=~\".*(loki|minio|promtail)*\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Received"
      },
      {
       "expr": "- sum(rate(container_network_transmit_packets_total{pod=~\".*(loki|minio|promtail)*\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Transmitted"
      }
     ]
    }
   ]
  }
 ]
}