{
 "title": "OPF Microservices RBHU Overview",
 "tags": [
  "Crisp- DevOps",
  "Monitoring",
  "RBHU",
  "OPF"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "OPF RBI Central", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RBICAS-RBI",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicas-cas-rbi.*\"} |= \"statusCode=\\\\\\\"200\\\\\\\"\" [$__interval]))",
     "legendFormat": "StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicas-cas-rbi.*\"} |= \"statusCode=\\\\\\\"500\" [$__interval]))",
     "legendFormat": "StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicas-cas-rbi.*\"} |= \"statusCode=\\\\\\\"400\" [$__interval]))",
     "legendFormat": "StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicas-cas-rbi.*\"} |= \"statusCode=\\\\\\\"401\" [$__interval]))",
     "legendFormat": "StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicas-cas-rbi.*\"} |= \"statusCode=\\\\\\\"403\" [$__interval]))",
     "legendFormat": "StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicas-cas-rbi.*\"} |= \"statusCode=\\\\\\\"404\" [$__interval]))",
     "legendFormat": "StatusCode 404"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicas-cas-rbi.*\"} |= \"statusCode=\\\\\\\"502\" [$__interval]))",
     "legendFormat": "StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicas-cas-rbi.*\"} |= \"statusCode=\\\\\\\"503\" [$__interval]))",
     "legendFormat": "StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicas-cas-rbi.*\"} |= \"statusCode=\\\\\\\"504\" [$__interval]))",
     "legendFormat": "StatusCode 504"
    }
   ]
  },
  {
   "title": "RBICBIS-CLOUD",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-deployment.*\"} |= \"status\\\\\\\":200\" [$__interval]))",
     "legendFormat": "reason code: VALIDATION_ERROR"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-deployment.*\"} |= \"status\\\\\\\":400\" [$__interval]))",
     "legendFormat": "StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-deployment.*\"} |= \"status\\\\\\\":500\" [$__interval]))",
     "legendFormat": "StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-deployment.*\"} |= \"code\\\\\\\":\\\\\\\"COMMON_BAD_REQUEST\" [$__interval]))",
     "legendFormat": "reason code:  COMMON_BAD_REQUEST"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-deployment.*\"} |= \"code\\\\\\\":\\\\\\\"Bad gateway\" [$__interval]))",
     "legendFormat": "reason code: Bad gateway"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-deployment.*\"} |= \"code\\\\\\\":\\\\\\\"COMMON_INTERNAL_ERROR\" [$__interval]))",
     "legendFormat": "reason code: COMMON_INTERNAL_ERROR"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-deployment.*\"} |= \"code\\\\\\\":\\\\\\\"INTERNAL_SERVER_ERROR\" [$__interval]))",
     "legendFormat": "reason code: INTERNAL_SERVER_ERROR"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-deployment.*\"} |= \"status\\\\\\\":401\" [$__interval]))",
     "legendFormat": "StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-deployment.*\"} |= \"status\\\\\\\":403\" [$__interval]))",
     "legendFormat": "StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-deployment.*\"} |= \"status\\\\\\\":404\" [$__interval]))",
     "legendFormat": "StatusCode 404"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-deployment.*\"} |= \"status\\\\\\\":502\" [$__interval]))",
     "legendFormat": "StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-deployment.*\"} |= \"status\\\\\\\":503\" [$__interval]))",
     "legendFormat": "StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-deployment.*\"} |= \"status\\\\\\\":504\" [$__interval]))",
     "legendFormat": "StatusCode 504"
    }
   ]
  },
  {
   "title": "RBIFXS-FXS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-fxs-rbi.*\"} |= \"statusCode=\\\\\\\"200\\\\\\\"\" [$__interval]))",
     "legendFormat": "StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-fxs-rbi.*\"} |= \"statusCode=\\\\\\\"400\\\\\\\"\" [$__interval]))",
     "legendFormat": "StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-fxs-rbi.*\"} |= \"statusCode=\\\\\\\"500\\\\\\\"\" [$__interval]))",
     "legendFormat": "StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-fxs-rbi.*\"} |= \"state\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"REJECTED\" [$__interval]))",
     "legendFormat": "state: REJECTED"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-fxs-rbi.*\"} |= \"statusCode=\\\\\\\"401\\\\\\\"\" [$__interval]))",
     "legendFormat": "StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-fxs-rbi.*\"} |= \"statusCode=\\\\\\\"403\\\\\\\"\" [$__interval]))",
     "legendFormat": "StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-fxs-rbi.*\"} |= \"statusCode=\\\\\\\"404\\\\\\\"\" [$__interval]))",
     "legendFormat": "StatusCode 404"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-fxs-rbi.*\"} |= \"statusCode=\\\\\\\"502\\\\\\\"\" [$__interval]))",
     "legendFormat": "StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-fxs-rbi.*\"} |= \"statusCode=\\\\\\\"503\\\\\\\"\" [$__interval]))",
     "legendFormat": "StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-fxs-rbi.*\"} |= \"statusCode=\\\\\\\"504\\\\\\\"\" [$__interval]))",
     "legendFormat": "StatusCode 504"
    }
   ]
  },
  {
   "title": "RBIPCS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-a-1.*\"} |= \"statusCode=\\\\\\\"200\\\\\\\"\" [$__interval]))",
     "legendFormat": "StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-a-1.*\"} |= \"statusCode=\\\\\\\"400\" [$__interval]))",
     "legendFormat": "StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-a-1.*\"} |= \"statusCode=\\\\\\\"500\" [$__interval]))",
     "legendFormat": "StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-a-1.*\"} |= \"\\\"BAD_REQUEST\\\\\" [$__interval]))",
     "legendFormat": "reason code: Bad Request"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-a-1.*\"} |= \"\\\"Technical Issue\\\\\" [$__interval]))",
     "legendFormat": "reason code: FAILED - Technical Issue"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-a-1.*\"} |= \"statusCode=\\\\\\\"401\" [$__interval]))",
     "legendFormat": "StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-a-1.*\"} |= \"statusCode=\\\\\\\"403\" [$__interval]))",
     "legendFormat": "StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-a-1.*\"} |= \"statusCode=\\\\\\\"404\" [$__interval]))",
     "legendFormat": "StatusCode 404"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-a-1.*\"} |= \"statusCode=\\\\\\\"502\" [$__interval]))",
     "legendFormat": "StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-a-1.*\"} |= \"statusCode=\\\\\\\"503\" [$__interval]))",
     "legendFormat": "StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-a-1.*\"} |= \"statusCode=\\\\\\\"504\" [$__interval]))",
     "legendFormat": "StatusCode 504"
    }
   ]
  },
  {
   "title": "RBIFSIS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifsis-a.*\"} |=  \"statusCode=\\\"200\" [$__interval]))",
     "legendFormat": "StatusCode 200 "
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifsis-a.*\"} |=  \"statusCode=\\\"400\" [$__interval]))",
     "legendFormat": "StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifsis-a.*\"} |=  \"statusCode=\\\"500\" [$__interval]))",
     "legendFormat": "StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifsis-a.*\"} |=  \"statusCode=\\\"401\" [$__interval]))",
     "legendFormat": "StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifsis-a.*\"} |=  \"statusCode=\\\"403\" [$__interval]))",
     "legendFormat": "StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifsis-a.*\"} |=  \"statusCode=\\\"404\" [$__interval]))",
     "legendFormat": "StatusCode 404"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifsis-a.*\"} |=  \"statusCode=\\\"502\" [$__interval]))",
     "legendFormat": "StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifsis-a.*\"} |=  \"statusCode=\\\"503\" [$__interval]))",
     "legendFormat": "StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifsis-a.*\"} |=  \"statusCode=\\\"504\" [$__interval]))",
     "legendFormat": "StatusCode 504"
    }
   ]
  },
  {
   "title": "RBISEPA-PEX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbisepa-pex.*\"} |= \"statusCode=\\\\\\\"200\\\\\\\"\" [$__interval]))",
     "legendFormat": "StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbisepa-pex.*\"} |= \"statusCode=\\\\\\\"400\" [$__interval]))",
     "legendFormat": "StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbisepa-pex.*\"} |= \"statusCode=\\\\\\\"500\" [$__interval]))",
     "legendFormat": "StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbisepa-pex.*\"} |= \"processingStatusCode\\\\\\\":\\\\\\\"PROCESSED\" [$__interval]))",
     "legendFormat": "Status: PROCESSED"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbisepa-pex.*\"} |= \"TECHNICAL_FAILURE\" [$__interval]))",
     "legendFormat": "responseCode: TECHNICAL_FAILURE"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbisepa-pex.*\"} |= \"processingStatusCode\\\\\\\":\\\\\\\"FAILED\" [$__interval]))",
     "legendFormat": "Status: FAILED"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbisepa-pex.*\"} |= \"statusCode=\\\\\\\"401\" [$__interval]))",
     "legendFormat": "StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbisepa-pex.*\"} |= \"statusCode=\\\\\\\"403\" [$__interval]))",
     "legendFormat": "StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbisepa-pex.*\"} |= \"statusCode=\\\\\\\"404\" [$__interval]))",
     "legendFormat": "StatusCode 404"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbisepa-pex.*\"} |= \"statusCode=\\\\\\\"502\" [$__interval]))",
     "legendFormat": "StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbisepa-pex.*\"} |= \"statusCode=\\\\\\\"503\" [$__interval]))",
     "legendFormat": "StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbisepa-pex.*\"} |= \"statusCode=\\\\\\\"504\" [$__interval]))",
     "legendFormat": "StatusCode 504"
    }
   ]
  },
  {
   "title": "RBIPOM-SCT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-pom-sct.*\"} |= \"statusCode=\\\\\\\"200\\\\\\\"\" [$__interval]))",
     "legendFormat": "StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-pom-sct.*\"} |= \"statusCode=\\\\\\\"400\" [$__interval]))",
     "legendFormat": "StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-pom-sct.*\"} |= \"statusCode=\\\\\\\"500\" [$__interval]))",
     "legendFormat": "StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-pom-sct.*\"} |= \"severity=\\\\\\\"ERROR\\\\\\\"\" [$__interval]))",
     "legendFormat": "severity=ERROR"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-pom-sct.*\"} |= \"statusCode=\\\\\\\"401\" [$__interval]))",
     "legendFormat": "StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-pom-sct.*\"} |= \"statusCode=\\\\\\\"403\" [$__interval]))",
     "legendFormat": "StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-pom-sct.*\"} |= \"statusCode=\\\\\\\"404\" [$__interval]))",
     "legendFormat": "StatusCode 404"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-pom-sct.*\"} |= \"statusCode=\\\\\\\"502\" [$__interval]))",
     "legendFormat": "StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-pom-sct.*\"} |= \"statusCode=\\\\\\\"503\" [$__interval]))",
     "legendFormat": "StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-pom-sct.*\"} |= \"statusCode=\\\\\\\"504\" [$__interval]))",
     "legendFormat": "StatusCode 504"
    }
   ]
  },
  {
   "title": "RBIXCT-PEX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbixct-pex.*\"} |= \"statusCode=\\\\\\\"200\\\\\\\"\" [$__interval]))",
     "legendFormat": "StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbixct-pex.*\"} |= \"statusCode=\\\\\\\"400\" [$__interval]))",
     "legendFormat": "StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbixct-pex.*\"} |= \"statusCode=\\\\\\\"500\" [$__interval]))",
     "legendFormat": "StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbixct-pex.*\"} |= \"processingStatusCode\\\\\\\":\\\\\\\"PROCESSED\" [$__interval]))",
     "legendFormat": "Status: PROCESSED"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbixct-pex.*\"} |= \"TECHNICAL_FAILURE\" [$__interval]))",
     "legendFormat": "responseCode: TECHNICAL_FAILURE"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbixct-pex.*\"} |= \"processingStatusCode\\\\\\\":\\\\\\\"FAILED\" [$__interval]))",
     "legendFormat": "Status: FAILED"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbixct-pex.*\"} |= \"statusCode=\\\\\\\"400\" [$__interval]))",
     "legendFormat": "StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbixct-pex.*\"} |= \"statusCode=\\\\\\\"400\" [$__interval]))",
     "legendFormat": "StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbixct-pex.*\"} |= \"statusCode=\\\\\\\"400\" [$__interval]))",
     "legendFormat": "StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbixct-pex.*\"} |= \"statusCode=\\\\\\\"500\" [$__interval]))",
     "legendFormat": "StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbixct-pex.*\"} |= \"statusCode=\\\\\\\"500\" [$__interval]))",
     "legendFormat": "StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbixct-pex.*\"} |= \"statusCode=\\\\\\\"500\" [$__interval]))",
     "legendFormat": "StatusCode 500"
    }
   ]
  },
  { "title": "OPF RBHU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "RBICBIS-RBHU-IMS-API-BACKEND",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apibackend.*\"} |= \"Successfully read 1 messages from queue 'RBHU.CBIS.API.TO.BACKEND.AE\" [$__interval]))",
     "legendFormat": "Read Messages 'RBHU.CBIS.API.TO.BACKEND.AE"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apibackend.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.CBIS.BACKEND.TO.API.OUTBOUND.POSTING\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.CBIS.BACKEND.TO.API.OUTBOUND.POSTING"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apibackend.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.CBIS.BACKEND.TO.API.OUTBOUND.AE\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.CBIS.BACKEND.TO.API.OUTBOUND.AE"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apibackend.*\"} |= \" ERROR RESTServer: Timeout request\" [$__interval]))",
     "legendFormat": "reason code: ERROR RESTServer: Timeout request"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apibackend.*\"} |= \" ERROR \" [$__interval]))",
     "legendFormat": "severity: ERROR"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 504\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 504"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 500\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 200\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 502\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 503\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 400\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 401\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 403\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 404\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 404"
    }
   ]
  },
  {
   "title": "RBIFXS-RBHU-IMS-API-BACKEND",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apibackend.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.FXS.BACKEND.TO.API.OUTBOUND\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.CBIS.API.OUTBOUND.BKP"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apibackend.*\"} |= \"Successfully read 1 messages from queue 'RBHU.FXS.API.TO.BACKEND\" [$__interval]))",
     "legendFormat": "Read Messages 'RBHU.CBIS.API.TO.BACKEND.AE"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apibackend.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.FXS.BACKEND.TO.API.INBOUND\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.FXS.BACKEND.TO.API.INBOUND"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apibackend.*\"} |= \" ERROR \" [$__interval]))",
     "legendFormat": "severity: ERROR"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 504\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 504"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 500\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 200\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 502\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 503\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 400\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 401\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 403\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 404\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 404"
    }
   ]
  },
  {
   "title": "RBICBIS-RBHU-IMS-API-GATEWAY-OUTBOUND-AE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-ae.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.CBIS.API.TO.BACKEND.AE\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.CBIS.API.TO.BACKEND.AE"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-ae.*\"} |= \"Successfully read 1 messages from queue 'RBHU.CBIS.BACKEND.TO.API.OUTBOUND.AE\" [$__interval]))",
     "legendFormat": "Read Messages 'RBHU.CBIS.BACKEND.TO.API.OUTBOUND.AE"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-ae.*\"} |= \" ERROR RESTServer: Timeout request\" [$__interval]))",
     "legendFormat": "reason code: ERROR RESTServer: Timeout request"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-ae.*\"} |= \" ERROR \" [$__interval]))",
     "legendFormat": "severity: ERROR"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-ae.*\"} |= \"HTTP/1.1 \\\" 504\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 504"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-ae.*\"} |= \"HTTP/1.1 \\\" 500\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-ae.*\"} |= \"HTTP/1.1 \\\" 200\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-ae.*\"} |= \"HTTP/1.1 \\\" 502\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-ae.*\"} |= \"HTTP/1.1 \\\" 503\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-ae.*\"} |= \"HTTP/1.1 \\\" 400\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-ae.*\"} |= \"HTTP/1.1 \\\" 401\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-ae.*\"} |= \"HTTP/1.1 \\\" 403\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-ae.*\"} |= \"HTTP/1.1 \\\" 404\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 404"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-ae.*\"} |= \"HTTP/1.1 \\\" 204\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 204"
    }
   ]
  },
  {
   "title": "RBIFXS-RBHU-IMS-API-GATEWAY-OUTBOUND",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.FXS.API.TO.BACKEND\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.FXS.API.TO.BACKEND"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"Successfully read 1 messages from queue 'RBHU.FXS.BACKEND.TO.API.OUTBOUND\" [$__interval]))",
     "legendFormat": "Read Messages 'RBHU.FXS.BACKEND.TO.API.OUTBOUND"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \" ERROR \" [$__interval]))",
     "legendFormat": "severity: ERROR"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 504\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 504"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 500\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 200\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 502\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 503\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 400\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 401\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 403\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 404\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 404"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"ERROR RESTServer: Timeout request\" [$__interval]))",
     "legendFormat": "reason code: ERROR RESTServer: Timeout request"
    }
   ]
  },
  {
   "title": "RBIPCS-RBHU-IMS-API-GATEWAY-OUTBOUND",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.CBIS.API.OUTBOUND.BKP\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.CBIS.API.OUTBOUND.BKP"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.CBIS.API.TO.BACKEND.AE\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.CBIS.API.TO.BACKEND.AE"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \" ERROR RESTServer: Timeout request\" [$__interval]))",
     "legendFormat": "reason code: ERROR RESTServer: Timeout request"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \" ERROR \" [$__interval]))",
     "legendFormat": "severity: ERROR"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 504\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 504"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 500\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 200\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 502\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 503\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 400\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 401\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 403\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 404\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 404"
    }
   ]
  },
  {
   "title": "RBIPOM-RBHU-IMS-API-GATEWAY-OUTBOUND",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.POM.API.TO.BACKEND\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.POM.API.TO.BACKEND"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"Successfully read 1 messages from queue 'RBHU.POM.BACKEND.TO.API.OUTBOUND\" [$__interval]))",
     "legendFormat": "Read Messages 'RBHU.POM.BACKEND.TO.API.OUTBOUND"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \" ERROR RESTServer: Timeout request\" [$__interval]))",
     "legendFormat": "reason code: ERROR RESTServer: Timeout request"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \" ERROR \" [$__interval]))",
     "legendFormat": "severity: ERROR"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 504\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 504"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 500\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 200\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 502\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 503\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 400\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 401\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 403\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayoutbound.*\"} |= \"HTTP/1.1 \\\" 404\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 404"
    }
   ]
  },
  {
   "title": "RBIPCS-RBHU-IMS-API-BACKEND",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apibackend.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.PCS.BACKEND.TO.API.OUTBOUND\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.PCS.BACKEND.TO.API.OUTBOUND'"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apibackend.*\"} |= \"Successfully read 1 messages from queue 'RBHU.PCS.API.TO.BACKEND\" [$__interval]))",
     "legendFormat": "Read Messages 'RBHU.PCS.API.TO.BACKEND'"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apibackend.*\"} |= \" ERROR \" [$__interval]))",
     "legendFormat": "severity: ERROR"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 504\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 504"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 500\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 200\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 502\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 503\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 400\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 401\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 403\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 404\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 404"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipcs-cloud-rbhu-ims-apibackend.*\"} |= \" ERROR RESTServer: Timeout request\" [$__interval]))",
     "legendFormat": "reason code: ERROR RESTServer: Timeout request"
    }
   ]
  },
  {
   "title": "RBIPOM-RBHU-IMS-API-GATEWAY-INBOUND",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.POM.API.TO.BACKEND\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.POM.API.TO.BACKEND"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"Successfully read 1 messages from queue 'RBHU.POM.BACKEND.TO.API.INBOUND\" [$__interval]))",
     "legendFormat": "Read Messages 'RBHU.POM.BACKEND.TO.API.INBOUND"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayinbound.*\"} |= \" ERROR RESTServer: Timeout request\" [$__interval]))",
     "legendFormat": "reason code: ERROR RESTServer: Timeout request"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayinbound.*\"} |= \" ERROR \" [$__interval]))",
     "legendFormat": "severity: ERROR"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 504\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 504"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 500\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 200\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 502\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 503\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 400\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 401\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 403\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 404\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 404"
    }
   ]
  },
  {
   "title": "RBICBIS-RBHU-IMS-API-GATEWAY-INBOUND",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.CBIS.API.OUTBOUND.BKP\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.CBIS.API.OUTBOUND.BKP"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.CBIS.API.TO.BACKEND.AE\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.CBIS.API.TO.BACKEND.AE"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayinbound.*\"} |= \" ERROR RESTServer: Timeout request\" [$__interval]))",
     "legendFormat": "reason code: ERROR RESTServer: Timeout request"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayinbound.*\"} |= \" ERROR \" [$__interval]))",
     "legendFormat": "severity: ERROR"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 504\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 504"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 500\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 200\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 502\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 503\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 400\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 401\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 403\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 404\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 404"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 204\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 204"
    }
   ]
  },
  {
   "title": "RBICBIS-RBHU-IMS-API-GATEWAY-OUTBOUND-POST",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-post.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.CBIS.API.OUTBOUND.BKP\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.CBIS.API.OUTBOUND.BKP"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-post.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.CBIS.API.TO.BACKEND.AE\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.CBIS.API.TO.BACKEND.AE"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-post.*\"} |= \" ERROR RESTServer: Timeout request\" [$__interval]))",
     "legendFormat": "reason code: ERROR RESTServer: Timeout request"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-post.*\"} |= \" ERROR \" [$__interval]))",
     "legendFormat": "severity: ERROR"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-post.*\"} |= \"HTTP/1.1 \\\" 504\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 504"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-post.*\"} |= \"HTTP/1.1 \\\" 500\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-post.*\"} |= \"HTTP/1.1 \\\" 200\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-post.*\"} |= \"HTTP/1.1 \\\" 502\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-post.*\"} |= \"HTTP/1.1 \\\" 503\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-post.*\"} |= \"HTTP/1.1 \\\" 400\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-post.*\"} |= \"HTTP/1.1 \\\" 401\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-post.*\"} |= \"HTTP/1.1 \\\" 403\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbicbis-cloud-rbhu-ims-apigatewayoutbound-post.*\"} |= \"HTTP/1.1 \\\" 404\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 404"
    }
   ]
  },
  {
   "title": "RBIFXS-RBHU-IMS-API-GATEWAY-INBOUND",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.FXS.API.TO.BACKEND\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.FXS.API.TO.BACKEND"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"Successfully read 1 messages from queue 'RBHU.FXS.BACKEND.TO.API.INBOUND\" [$__interval]))",
     "legendFormat": "Read Messages 'RBHU.CBIS.API.TO.BACKEND.AE"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayinbound.*\"} |= \" ERROR \" [$__interval]))",
     "legendFormat": "severity: ERROR"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 504\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 504"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 500\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 200\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 502\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 503\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 400\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 401\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 403\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 404\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 404"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbifxs-cloud-rbhu-ims-apigatewayinbound.*\"} |= \"HTTP/1.1 \\\" 204\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 204"
    }
   ]
  },
  {
   "title": "RBIPOM-RBHU-IMS-API-BACKEND",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apibackend.*\"} |= \"Successfully committed 1 message(s) for queue 'RBHU.POM.BACKEND.TO.API.OUTBOUND\" [$__interval]))",
     "legendFormat": "Committed Messages 'RBHU.POM.BACKEND.TO.API.OUTBOUND"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apibackend.*\"} |= \"Successfully read 1 messages from queue 'RBHU.POM.API.TO.BACKEND\" [$__interval]))",
     "legendFormat": "Read Messages 'RBHU.POM.API.TO.BACKEND"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apibackend.*\"} |= \" ERROR RESTServer: Timeout request\" [$__interval]))",
     "legendFormat": "reason code: ERROR RESTServer: Timeout request"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apibackend.*\"} |= \" ERROR \" [$__interval]))",
     "legendFormat": "severity: ERROR"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 504\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 504"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 500\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 500"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 200\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 200"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 502\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 502"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 503\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 503"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 400\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 400"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 401\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 401"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 403\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 403"
    },
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"rbipom-cloud-rbhu-ims-apibackend.*\"} |= \"HTTP/1.1 \\\" 404\" [$__interval]))",
     "legendFormat": "HTTP StatusCode 404"
    }
   ]
  }
 ]
}