{
 "title": "Monitoring System / Prometheus",
 "description": "This is a modern 'Prometheus' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus",
  "Crisp- DevOps"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(prometheus_build_info{cluster=\"$cluster\"}, pod)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(prometheus_build_info{cluster=\"$cluster\"},namespace)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (version) (prometheus_build_info)",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Prometheus Down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{pod=~\"$pod\", cluster=~\"$cluster\"} < 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kube-state-metrics version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "p", "legendFormat": "{{ version }}" }
   ]
  },
  {
   "title": "Metrics Down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"kube-state-metrics\"} < 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rules Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_rule_group_rules)"
    }
   ]
  },
  {
   "title": "TSDB Head Series",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{pod=~\"$pod\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discovered Targets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{pod=~\"$pod\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alertmanager version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (version) (alertmanager_build_info)",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Alertmanager Down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=~\".*alertmanager.*\"} < 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node-exporter version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (version) (node_exporter_build_info)",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "node-exporter Down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"node-exporter\"} < 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitoring Resource Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_configmap_info)", "legendFormat": "Service Monitors" },
    { "expr": "count(kube_configmap_info)", "legendFormat": "Pod Monitors" },
    {
     "expr": "sum(kube_ingress_info{namespace=\"$namespace\"})",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{namespace=\"$namespace\"})",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(kube_hpa_labels{namespace=\"$namespace\"})",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(kube_configmap_info{namespace=\"$namespace\"})",
     "legendFormat": "Datasources"
    },
    {
     "expr": "sum(kube_secret_info{namespace=\"$namespace\"})",
     "legendFormat": "Dashboards"
    },
    {
     "expr": "sum(kube_node_spec_taint{key=\"ForMonitoring\"})",
     "legendFormat": "Monitoring Pool Nodes"
    }
   ]
  },
  {
   "title": "Grafana version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "grafana_build_info", "legendFormat": "{{ version }}" }
   ]
  },
  {
   "title": "Grafana Down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=~\".*grafana.*\"} < 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "blackbox-exporter version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "blackbox_exporter_build_info", "legendFormat": "{{ version }}" }
   ]
  },
  {
   "title": "blackbox-exp Down",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"blackbox\"} < 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Helm chart version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Liveness by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{pod=~\"(prometheus-.*|alertmanager-.*)\", pod!~\".*loki.*\", pod!~\".*minio.*\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Config - Last Successful Reload by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_config_last_reload_successful{pod=~\"$pod\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Target Scrapes Errors by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_scrapes_exceeded_body_size_limit_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Exceeded body size limit"
    },
    {
     "expr": "sum(rate(prometheus_target_scrapes_exceeded_sample_limit_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Exceeded sample limit"
    },
    {
     "expr": "sum(rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Duplicate timestamp"
    },
    {
     "expr": "sum(rate(prometheus_target_scrapes_sample_out_of_bounds_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Sample out of bounds"
    },
    {
     "expr": "sum(rate(prometheus_target_scrapes_sample_out_of_order_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Sample out of order"
    }
   ]
  },
  {
   "title": "Number of Targets by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{pod=~\"$pod\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Target Sync by pod, scrape_job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod, scrape_job) * 1000",
     "legendFormat": "{{ pod }} - {{ scrape_job }}"
    }
   ]
  },
  {
   "title": "Average Scrape Interval by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "round(sum(rate(prometheus_target_interval_length_seconds_sum{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval]) / rate(prometheus_target_interval_length_seconds_count{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Prometheus TSDB / Query Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "TSDB Head Series & Chunks by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(prometheus_tsdb_head_series{pod=~\"$pod\", cluster=~\"$cluster\"}) by (pod)",
       "legendFormat": "{{ pod }} - Head Series"
      },
      {
       "expr": "sum(prometheus_tsdb_head_chunks{pod=~\"$pod\", cluster=~\"$cluster\"}) by (pod)",
       "legendFormat": "{{ pod }} - Head Chunks"
      }
     ]
    },
    {
     "title": "TSDB Head samples appended - rate by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "TSDB Blocks Loaded by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(prometheus_tsdb_blocks_loaded{pod=~\"$pod\", cluster=~\"$cluster\"}) by (pod)",
       "legendFormat": "{{ pod }} - Head Series"
      }
     ]
    },
    {
     "title": "TSDB Rate of Compactions by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_tsdb_compactions_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Total Compactions"
      },
      {
       "expr": "sum(rate(prometheus_tsdb_compactions_triggered_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Triggered Compactions"
      },
      {
       "expr": "sum(rate(prometheus_tsdb_compactions_skipped_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Skipped Compactions"
      },
      {
       "expr": "sum(rate(prometheus_tsdb_compactions_failed_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Failed Compactions"
      }
     ]
    },
    {
     "title": "TSDB Reload Failures by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_tsdb_reloads_failures_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "TSDB Created & Deleted series by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_tsdb_head_series_created_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Created series"
      },
      {
       "expr": "sum(rate(prometheus_tsdb_head_series_removed_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Deleted series"
      }
     ]
    },
    {
     "title": "Engine Query Count by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_engine_query_duration_seconds_count{pod=~\"$pod\", slice=\"inner_eval\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Engine Query Duration by pod, slice",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(prometheus_engine_query_duration_seconds{pod=~\"$pod\", cluster=~\"$cluster\"}) by (pod, slice) * 1000",
       "legendFormat": "{{ pod }} - {{ slice }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage by pod, container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"(prometheus-.*|alertmanager-.*)\", pod!~\".*loki.*\", pod!~\".*minio.*\", pod!~\".*promtail.*\", image!=\"\", container!=\"\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod, container)",
       "legendFormat": "{{ pod }} - {{ container }}"
      }
     ]
    },
    {
     "title": "Memory Usage by container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{pod=~\"(prometheus-.*|alertmanager-.*)\", pod!~\".*loki.*\", pod!~\".*minio.*\", pod!~\".*promtail.*\", image!=\"\", container!=\"\", cluster=~\"$cluster\"}) by (pod, container)",
       "legendFormat": "{{ pod }} - {{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Persistent Volumes - Capacity and usage in %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*db-prom.*\", cluster=~\"$cluster\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*db-prom.*\", cluster=~\"$cluster\"}) by (persistentvolumeclaim)",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    },
    {
     "title": "Persistent Volumes - Capacity and usage in bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*db-prom.*\", cluster=~\"$cluster\"}) by (persistentvolumeclaim)",
       "legendFormat": "{{ persistentvolumeclaim }} - Used"
      },
      {
       "expr": "sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*db-prom.*\", cluster=~\"$cluster\"}) by (persistentvolumeclaim)",
       "legendFormat": "{{ persistentvolumeclaim }} - Capacity"
      }
     ]
    },
    {
     "title": "Persistent Volumes - Inodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - sum(kubelet_volume_stats_inodes_used{persistentvolumeclaim=~\".*db-prom.*\", cluster=~\"$cluster\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_inodes{persistentvolumeclaim=~\".*db-prom.*\", cluster=~\"$cluster\"}) by (persistentvolumeclaim)",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network - Bandwidth by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"(prometheus-.*|alertmanager-.*)\", pod!~\".*loki.*\", pod!~\".*minio.*\", pod!~\".*promtail.*\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Received"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{pod=~\"(prometheus-.*|alertmanager-.*)\", pod!~\".*loki.*\", pod!~\".*minio.*\", pod!~\".*promtail.*\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Transmitted"
      }
     ]
    },
    {
     "title": "Network - Errors by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_errors_total{pod=~\"(prometheus-.*|alertmanager-.*)\", pod!~\".*loki.*\", pod!~\".*minio.*\", pod!~\".*promtail.\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Received"
      },
      {
       "expr": "- sum(rate(container_network_transmit_errors_total{pod=~\"(prometheus-.*|alertmanager-.*)\", pod!~\".*loki.*\", pod!~\".*minio.*\", pod!~\".*promtail.*\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Transmitted"
      }
     ]
    },
    {
     "title": "Network - Packets Dropped by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{pod=~\"(prometheus-.*|alertmanager-.*)\", pod!~\".*loki.*\", pod!~\".*minio.*\", pod!~\".*promtail.*\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Received"
      },
      {
       "expr": "- sum(rate(container_network_transmit_packets_dropped_total{pod=~\"(prometheus-.*|alertmanager-.*)\", pod!~\".*loki.*\", pod!~\".*minio.*\", pod!~\".*promtail.*\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Transmitted"
      }
     ]
    },
    {
     "title": "Network - Packets rate by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{pod=~\"(prometheus-.*|alertmanager-.*)\", pod!~\".*loki.*\", pod!~\".*minio.*\", pod!~\".*promtail.*\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Received"
      },
      {
       "expr": "- sum(rate(container_network_transmit_packets_total{pod=~\"(prometheus-.*|alertmanager-.*)\", pod!~\".*loki.*\", pod!~\".*minio.*\", pod!~\".*promtail.*\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{ pod }} - Transmitted"
      }
     ]
    }
   ]
  }
 ]
}