{
 "title": "OPF RBI Service Health Monitoring",
 "tags": [
  "Crisp- DevOps",
  "OPF",
  "Monitoring",
  "RBI"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(probe_http_status_code{job=\"blackbox-external-sit-readiness\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SIT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RBICAS Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\",instance=\"https://rbicas-cloud.sit.crisp.rbro.rbg.cc/cas/v1/pod/readiness\"}",
     "legendFormat": "Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",instance=\"https://rbicas-cloud.sit.crisp.rbro.rbg.cc/cas/v1/pod/readiness\"}",
     "legendFormat": "ResponseCode"
    },
    {
     "expr": "probe_duration_seconds{job=\"$job\",instance=\"https://rbicas-cloud.sit.crisp.rbro.rbg.cc/cas/v1/pod/readiness\"}",
     "legendFormat": "ExecTime"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RBIFSIS Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\",instance=\"https://rbifsis-cloud.sit.crisp.rbro.rbg.cc/fsis/v1/pod/readiness\"}",
     "legendFormat": "Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",instance=\"https://rbifsis-cloud.sit.crisp.rbro.rbg.cc/fsis/v1/pod/readiness\"}",
     "legendFormat": "ResponseCode"
    },
    {
     "expr": "probe_duration_seconds{job=\"$job\",instance=\"https://rbifsis-cloud.sit.crisp.rbro.rbg.cc/fsis/v1/pod/readiness\"}",
     "legendFormat": "ExecTime"
    }
   ]
  },
  {
   "title": "RBIPCS Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\",instance=\"https://rbipcs-cloud.sit.crisp.rbro.rbg.cc/pcs/v1/pod/readiness\"}",
     "legendFormat": "Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",instance=\"https://rbipcs-cloud.sit.crisp.rbro.rbg.cc/pcs/v1/pod/readiness\"}",
     "legendFormat": "ResponseCode"
    },
    {
     "expr": "probe_duration_seconds{job=\"$job\",instance=\"https://rbipcs-cloud.sit.crisp.rbro.rbg.cc/pcs/v1/pod/readiness\"}",
     "legendFormat": "ExecTime"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RBIXCT   Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\",instance=\"https://rbixct-cloud.sit.crisp.rbro.rbg.cc/xctrest/webapi/v1/probes/ready\"}",
     "legendFormat": "Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",instance=\"https://rbixct-cloud.sit.crisp.rbro.rbg.cc/xctrest/webapi/v1/probes/ready\"}",
     "legendFormat": "ResponseCode"
    },
    {
     "expr": "probe_duration_seconds{job=\"$job\",instance=\"https://rbixct-cloud.sit.crisp.rbro.rbg.cc/xctrest/webapi/v1/probes/ready\"}",
     "legendFormat": "ExecTime"
    }
   ]
  },
  {
   "title": "RBIPCS Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\",instance=\"https://rbipcs-cloud.sit.crisp.rbro.rbg.cc/pcs/v1/pod/readiness\"}",
     "legendFormat": "Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",instance=\"https://rbipcs-cloud.sit.crisp.rbro.rbg.cc/pcs/v1/pod/readiness\"}",
     "legendFormat": "ResponseCode"
    },
    {
     "expr": "probe_duration_seconds{job=\"$job\",instance=\"https://rbipcs-cloud.sit.crisp.rbro.rbg.cc/pcs/v1/pod/readiness\"}",
     "legendFormat": "ExecTime"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RBIPOM  Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\",instance=\"https://rbipom-cloud.sit.crisp.rbro.rbg.cc/pom-sct/v1/pod/readiness\"}",
     "legendFormat": "Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",instance=\"https://rbipom-cloud.sit.crisp.rbro.rbg.cc/pom-sct/v1/pod/readiness\"}",
     "legendFormat": "ResponseCode"
    },
    {
     "expr": "probe_duration_seconds{job=\"$job\",instance=\"https://rbipom-cloud.sit.crisp.rbro.rbg.cc/pom-sct/v1/pod/readiness\"}",
     "legendFormat": "ExecTime"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RBISEPA Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\",instance=\"https://rbisepa-cloud.uat.crisp.rbro.rbg.cc/opfrest/webapi/v1/probes/ready\"}",
     "legendFormat": "Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",instance=\"https://rbisepa-cloud.uat.crisp.rbro.rbg.cc/opfrest/webapi/v1/probes/ready\"}",
     "legendFormat": "ResponseCode"
    },
    {
     "expr": "probe_duration_seconds{job=\"$job\",instance=\"https://rbisepa-cloud.uat.crisp.rbro.rbg.cc/opfrest/webapi/v1/probes/ready\"}",
     "legendFormat": "ExecTime"
    },
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "UAT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RBICAS Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\",instance=\"https://rbicas-cloud.uat.crisp.rbro.rbg.cc/cas/v1/pod/readiness\"}",
     "legendFormat": "Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",instance=\"https://rbicas-cloud.uat.crisp.rbro.rbg.cc/cas/v1/pod/readiness\"}",
     "legendFormat": "ResponseCode"
    },
    {
     "expr": "probe_duration_seconds{job=\"$job\",instance=\"https://rbicas-cloud.uat.crisp.rbro.rbg.cc/cas/v1/pod/readiness\"}",
     "legendFormat": "ExecTime"
    }
   ]
  },
  {
   "title": "RBIFSIS Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\",instance=\"https://rbifsis-cloud.uat.crisp.rbro.rbg.cc/fsis/v1/pod/readiness\"}",
     "legendFormat": "Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",instance=\"https://rbifsis-cloud.uat.crisp.rbro.rbg.cc/fsis/v1/pod/readiness\"}",
     "legendFormat": "ResponseCode"
    },
    {
     "expr": "probe_duration_seconds{job=\"$job\",instance=\"https://rbifsis-cloud.uat.crisp.rbro.rbg.cc/fsis/v1/pod/readiness\"}",
     "legendFormat": "ExecTime"
    }
   ]
  },
  {
   "title": "RBIPCS Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\",instance=\"https://rbipcs-cloud.uat.crisp.rbro.rbg.cc/pcs/v1/pod/readiness\"}",
     "legendFormat": "Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",instance=\"https://rbipcs-cloud.uat.crisp.rbro.rbg.cc/pcs/v1/pod/readiness\"}",
     "legendFormat": "ResponseCode"
    },
    {
     "expr": "probe_duration_seconds{job=\"$job\",instance=\"https://rbipcs-cloud.uat.crisp.rbro.rbg.cc/pcs/v1/pod/readiness\"}",
     "legendFormat": "ExecTime"
    }
   ]
  },
  {
   "title": "RBIXCT   Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\",instance=\"https://rbixct-cloud.uat.crisp.rbro.rbg.cc/xctrest/webapi/v1/probes/ready\"}",
     "legendFormat": "Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",instance=\"https://rbixct-cloud.uat.crisp.rbro.rbg.cc/xctrest/webapi/v1/probes/ready\"}",
     "legendFormat": "ResponseCode"
    },
    {
     "expr": "probe_duration_seconds{job=\"$job\",instance=\"https://rbixct-cloud.uat.crisp.rbro.rbg.cc/xctrest/webapi/v1/probes/ready\"}",
     "legendFormat": "ExecTime"
    }
   ]
  },
  {
   "title": "RBIFXS Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\",instance=\"https://rbifxs-cloud.uat.crisp.rbro.rbg.cc/fxs/v1/pod/readiness\"}",
     "legendFormat": "Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",instance=\"https://rbifxs-cloud.uat.crisp.rbro.rbg.cc/fxs/v1/pod/readiness\"}",
     "legendFormat": "ResponseCode"
    },
    {
     "expr": "probe_duration_seconds{job=\"$job\",instance=\"https://rbifxs-cloud.uat.crisp.rbro.rbg.cc/fxs/v1/pod/readiness\"}",
     "legendFormat": "ExecTime"
    }
   ]
  },
  {
   "title": "RBIPOM  Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\",instance=\"https://rbipom-cloud.uat.crisp.rbro.rbg.cc/pom-sct/v1/pod/readiness\"}",
     "legendFormat": "Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",instance=\"https://rbipom-cloud.uat.crisp.rbro.rbg.cc/pom-sct/v1/pod/readiness\"}",
     "legendFormat": "ResponseCode"
    },
    {
     "expr": "probe_duration_seconds{job=\"$job\",instance=\"https://rbipom-cloud.uat.crisp.rbro.rbg.cc/pom-sct/v1/pod/readiness\"}",
     "legendFormat": "ExecTime"
    }
   ]
  },
  {
   "title": "RBISEPA Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\",instance=\"https://rbisepa-cloud.uat.crisp.rbro.rbg.cc/opfrest/webapi/v1/probes/ready\"}",
     "legendFormat": "Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",instance=\"https://rbisepa-cloud.uat.crisp.rbro.rbg.cc/opfrest/webapi/v1/probes/ready\"}",
     "legendFormat": "ResponseCode"
    },
    {
     "expr": "probe_duration_seconds{job=\"$job\",instance=\"https://rbisepa-cloud.uat.crisp.rbro.rbg.cc/opfrest/webapi/v1/probes/ready\"}",
     "legendFormat": "ExecTime"
    }
   ]
  },
  {
   "title": "RBICBIS Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\",instance=\"https://rbicbis-cloud.uat.crisp.rbro.rbg.cc/cbis/api/operations/v4/healthunsecured\"}",
     "legendFormat": "Endpoint"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",instance=\"https://rbicbis-cloud.uat.crisp.rbro.rbg.cc/cbis/api/operations/v4/healthunsecured\"}",
     "legendFormat": "ResponseCode"
    },
    {
     "expr": "probe_duration_seconds{job=\"$job\",instance=\"https://rbicbis-cloud.uat.crisp.rbro.rbg.cc/cbis/api/operations/v4/healthunsecured\"}",
     "legendFormat": "ExecTime"
    }
   ]
  }
 ]
}